steps:
  - template: ../templates/coretide_initialization.yml
  - script: | 
      git rebase origin/$(OpenTide.DefaultBranch)
      cd coretide/Orchestration/
      python deploy.py
    env: 
      MDE_CLIENT_SECRET: $(MDE_CLIENT_SECRET)
      DEPLOYMENT_PLAN: PRODUCTION
    displayName: Deployment Routine
  - script: | 
      rm -rf coretide
    displayName: Remove CoreTide Repository
  - script: |
      [[ $(git status --porcelain) ]] || { echo "No changes, exiting"; exit 0; }
      echo "Updated files, committing"
      git rebase
      git add -A
      git commit -m "Detection Rules Auto-Promotion"
      git push origin
    displayName: Commit Promotion if Changes