steps:
  - template: ../templates/coretide_initialization.yml
  - script: |
      set -a
      source $(Pipeline.Workspace)/.env
      set -a
      cd coretide/Orchestration
      python deploy.py
    env: 
      DEPLOYMENT_PLAN: STAGING
    displayName: Deployment Routine