models = [ "tvm", "cdm", "dom", "bdr", "mdr" ]

[paths.tide]
tvm = "Objects/Threat Vectors/"
cdm = "Objects/Detection Models/"
mdr = "Objects/Detection Rules/"
bdr = "Objects/Business Detections/"
dom = "Objects/Detection Objectives/"
lookups = "Lookups/"
analytics = "Analytics/"
snippet_file = ".vscode/Model Templates.code-snippets"
json_schemas = "Schemas/"
templates = "Schemas/Templates/"
tide_indexes = "Schemas/Indexes/"
custom_configurations = "Configurations/"

[paths.core]
staging_index_output = "staging_index.json"
index_output = "index.json"
vocabularies = "Framework/Vocabulary/"
configurations = "Configurations/"
metaschemas = "Framework/Meta Schemas/"
subschemas = "Framework/Meta Schemas/Sub Schemas/"
definitions = "Framework/Meta Schemas/Definitions/"
wiki_docs_folder = "wiki/"
models_docs_folder = "wiki/Models/"
schemas_docs_folder = "wiki/Framework/Schemas/"
vocabularies_docs = "wiki/Framework/Vocabularies/"
resources = "External/"

[metaschemas]
tvm = "TVM Meta Schema.yaml"
cdm = "CDM Meta Schema.yaml"
mdr = "MDR Meta Schema.yaml"
bdr = "BDR Meta Schema.yaml"
dom = "Detection Objectives.meta.yaml"
lookup_metadata = "Lookup Metadata Meta Schema.yaml"

[recomposition]
systems = "MDR Systems Deployment"

[json_schemas]
tvm = "TVM Schema.json"
cdm = "CDM Schema.json"
mdr = "MDR Schema.json"
bdr = "BDR Schema.json"
dom = "Detection Objectives.schema.json"
lookup_metadata = "Lookup Metadata Schema.json"

[data_fields]
tvm = "threat"
cdm = "detection"
mdr = "rule"
bdr = "request"
dom = "objective"

[templates]
tvm = "TVM TEMPLATE.yaml"
cdm = "CDM TEMPLATE.yaml"
mdr = "MDR TEMPLATE.yaml"
bdr = "BDR TEMPLATE.yaml"
dom = "Detection Objective.template.yaml"
lookup_metadata = "LOOKUP METADATA TEMPLATE.yaml"
