name: "Detect MDR Changes"
description: "Detect any changes to managed detection rules"
outputs:
  mdr_changes:
    description: "Whether detection rules have changed"
    value: ${{ steps.detect_mdr_changes.outputs.CHANGES }}
runs:
  using: "composite"
  steps:
    - name: Detect changes
      id: detect_mdr_changes
      shell: bash
      run: |
          # List files changed in the last commit compared to parent.
          # The parent must exist
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED=$(git diff --name-only HEAD^ HEAD)
            
            echo "Changed files: $CHANGED"
            # Grep for the directory with a leading ^ to avoid false positives
            if echo "$CHANGED" | grep -q '^Objects/Detection Rules/'; then
              echo "CHANGES=true" >> $GITHUB_OUTPUT
            else
              echo "CHANGES=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          fi
