name: "Query Validation"
description: "Run OpenTide Query Validation"

inputs:
  deployment_plan:
    description: "STAGING/PRODUCTION"

runs:
  using: "composite"
  steps:
    - name: Validate Query
      id: validate_query
      shell: bash
      run: |
        export DEPLOYMENT_PLAN=${{ inputs.deployment_plan }}
        export CI_PROJECT_DIR=$(pwd)
        export MAIN_HEAD_SHA=$(git rev-parse main) 
        export MAIN_HEAD_SHA_PREVIOUS=$(git rev-parse 'main~1') 
        # Supported plan : ['STAGING', 'PRODUCTION', 'FULL', 'ALWAYS', 'MANUAL', 'DEBUG']
        cd coretide/Orchestration
        python validate_query.py
