name: "Deployment Routing"
description: "Deploy the object that are changed"

inputs:
  azure_workspace_id:
    description: "Azure Workspace ID"
    required: false
  azure_subscription_id:
    description: "Azure Subscription ID"
    required: false
  azure_tenant_id:
    description: "Azure Tenant ID"
    required: false
  azure_client_id:
    description: "Azure Client ID"
    required: false
  azure_client_secret:
    description: "Azure Client Secret"
    required: false
  deployment_plan:
    description: "Deployment Plan"
    required: false

runs:
  using: "composite"
  steps:
    - name: Deployment Routine
      shell: bash
      run: |
        export AZURE_WORKSPACE_ID=${{ inputs.azure_workspace_id }}
        export AZURE_SUBSCRIPTION_ID=${{ inputs.azure_subscription_id }}
        export AZURE_TENANT_ID=${{ inputs.azure_tenant_id }}
        export AZURE_CLIENT_ID=${{ inputs.azure_client_id }}
        export AZURE_CLIENT_SECRET=${{ inputs.azure_client_secret }}
        export DEPLOYMENT_PLAN=${{ inputs.deployment_plan }}
        export CI_PROJECT_DIR=$(pwd)
        export MAIN_HEAD_SHA=$(git rev-parse main) 
        export MAIN_HEAD_SHA_PREVIOUS=$(git rev-parse 'main~1')

        cd coretide/Orchestration
        python deploy.py
