name: "Deployment Routing"
description: "Deploy the object that are changed"

inputs:
  deployment_plan:
    description: "Deployment Plan"
    required: false

runs:
  using: "composite"
  steps:
    - name: Deployment Routine
      shell: bash
      run: |
        cd coretide/Orchestration
        python deploy.py
      env:
        DEPLOYMENT_PLAN: ${{ inputs.deployment_plan }}