name: Deployment

on:
  workflow_call:
    inputs:
      azure_workspace_id:
        type: string
        description: "Azure Workspace ID"
        required: false
      azure_subscription_id:
        type: string
        description: "Azure Subscription ID"
        required: false
      azure_tenant_id:
        type: string
        description: "Azure Tenant ID"
        required: false
      azure_client_id:
        type: string
        description: "Azure Client ID"
        required: false
      azure_client_secret:
        type: string
        description: "Azure Client Secret"
        required: false
      deployment_plan:
        type: string
        description: "Deployment Plan"
        required: false
      coretide_path:
        type: string
        description: "Path where CoreTide needs to be cloned into"
        required: false
        default: coretide
      coretide_ref:
        type: string
        description: "Ref to clone CoreTide from"
        required: false
        default: refs/heads/main
      python_version:
        type: string
        description: "Python version to use"
        required: false
        default: "3.12"
      requirements_file:
        type: string
        description: "Requirements file path"
        required: false
        default: "coretide/Engines/requirements.txt"

jobs:
  Deployment:
    name: Deploy
    # if: ${{ github.ref == 'refs/heads/main' && needs.Validation.outputs.CHANGES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: ${{ inputs.coretide_path }}
          ref: ${{ inputs.coretide_ref }}

      - name: Tide Setup
        uses: ./coretide/Pipelines/GitHub/tide-setup
        id: tide_setup
        with:
          python-version: ${{ inputs.python_version }}
          requirements-file: ${{ inputs.requirements_file }}

      - uses: ./coretide/Pipelines/GitHub/deployment
        name: Deployment Routine
        id: deployment_routine
