name: Deployment

on:
  workflow_call:

jobs:
  Deployment:
    name: Deploy
    # if: ${{ github.ref == 'refs/heads/main' && needs.Validation.outputs.CHANGES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: coretide
          ref: refs/heads/feature/github-action-support

      - name: Tide Setup
        uses: ./coretide/Pipelines/GitHub/tide-setup
        id: tide_setup
        with:
          coretide-ref: "refs/heads/development"
          coretide-path: "coretide"
          python-version: "3.12"
          requirements-file: "coretide/Engines/requirements.txt"
          git-user-name: "${{ github.actor }}"
          git-user-email: "${{ github.actor }}@users.noreply.github.com"

      - name: Deployment Routine
        shell: bash
        run: |
          export MDE_TENANT_ID=test-placeholder-tenant-id
          export MDE_CLIENT_ID=test-placeholder-client-id
          export MDE_CLIENT_SECRET=test-placeholder-client
          export AZURE_WORKSPACE_ID=test-placeholder-client
          export AZURE_SUBSCRIPTION_ID=test-placeholder-client
          export AZURE_TENANT_ID=test-placeholder-client
          export AZURE_CLIENT_ID=test-placeholder-client
          export AZURE_CLIENT_SECRET=test-placeholder-client
          export MDE_TENANT_ID=test-placeholder-tenant-id
          export DEPLOYMENT_PLAN=PRODUCTION
          cd coretide/Orchestration
          python deploy.py
