name: Deployment

on:
  workflow_call:
    inputs:
      azure_workspace_id:
        type: string
        description: "Azure Workspace ID"
        required: false
      azure_subscription_id:
        type: string
        description: "Azure Subscription ID"
        required: false
      azure_tenant_id:
        type: string
        description: "Azure Tenant ID"
        required: false
      azure_client_id:
        type: string
        description: "Azure Client ID"
        required: false
      azure_client_secret:
        type: string
        description: "Azure Client Secret"
        required: false
      deployment_plan:
        type: string
        description: "Deployment Plan"
        required: false
      coretide_path:
        type: string
        description: "Path where CoreTide needs to be cloned into"
        required: false
        default: coretide
      coretide_ref:
        type: string
        description: "Ref to clone CoreTide from"
        required: false
        default: refs/heads/main
      python_version:
        type: string
        description: "Python version to use"
        required: false
        default: "3.12"
      requirements_file:
        type: string
        description: "Requirements file path"
        required: false
        default: "coretide/Engines/requirements.txt"

jobs:
  Deployment:
    name: Deploy
    # if: ${{ github.ref == 'refs/heads/main' && needs.Validation.outputs.CHANGES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: ${{ inputs.coretide_path }}
          ref: ${{ inputs.coretide_ref }}

      - name: Tide Setup
        uses: ./coretide/Pipelines/GitHub/tide-setup
        id: tide_setup
        with:
          python_version: ${{ inputs.python_version }}
          requirements_file: ${{ inputs.requirements_file }}

      - name: set_secrets
        shell: bash
        run: |
          cat ${{ env }}
          cat env
          env
          env | sort | while IFS= read -r line; do
            if [[ "$line" == *"="* ]]; then
              key=$(echo "$line" | cut -d '=' -f 1)
              value=$(echo "$line" | cut -d '=' -f 2-)
              value=$(echo "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
              echo "$key=\"$value\"" >> $GITHUB_OUTPUT
            else
              echo "$line" >> $GITHUB_OUTPUT
            fi
          done
          cat $GITHUB_OUTPUT

      - uses: ./coretide/Pipelines/GitHub/deployment
        name: Deployment Routine
        id: deployment_routine
        with:
          azure_workspace_id: ${{ inputs.azure_workspace_id }}
          azure_subscription_id: ${{ inputs.azure_subscription_id }}
          azure_tenant_id: ${{ inputs.azure_tenant_id }}
          azure_client_id: ${{ inputs.azure_client_id }}
          azure_client_secret: ${{ inputs.azure_client_secret }}
          deployment_plan: ${{ inputs.deployment_plan }}
