name: Framework Generation Pipeline

on:
  workflow_call:
    inputs:
      deployment_plan:
        type: string
        description: "Deployment Plan"
        required: false
      coretide_path:
        type: string
        description: "Path where CoreTide needs to be cloned into"
        required: false
        default: coretide
      coretide_ref:
        type: string
        description: "Ref to clone CoreTide from"
        required: false
        default: development
      python_version:
        type: string
        description: "Python version to use"
        required: false
        default: "3.12"
      requirements_file:
        type: string
        description: "Requirements file path"
        required: false
        default: "coretide/Engines/requirements.txt"
      opentide_secrets:
        type: string
        description: "Content of the OpenTide secrets file"
        required: false
        default: "" 

jobs:
  Framework:
    name: Framework Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: ${{ inputs.coretide_path }}
          ref: refs/heads/${{ inputs.coretide_ref }}

      - uses: ./coretide/Pipelines/GitHub/tide-setup
        name: Tide Setup
        id: tide_setup
        with:
          python_version: ${{ inputs.python_version }}
          requirements_file: ${{ inputs.requirements_file }}
          opentide_secrets: ${{ inputs.opentide_secrets }}

      - uses: ./coretide/Pipelines/GitHub/framework-setup
        name: Framework Setup
        id: framework_setup
        with:
          coretide_path: ${{ inputs.coretide_path }}
