name: Framework Generation Pipeline

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
      requirements_file:
        type: string
        required: true
      coretide_ref:
        type: string
        required: true
      coretide_path:
        type: string
        required: true

jobs:
  Framework:
    name: Framework Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: ${{ inputs.coretide_path }}
          ref: ${{ inputs.coretide_ref }}

      - uses: ./coretide/Pipelines/GitHub/tide-setup
        name: Tide Setup
        id: tide_setup
        with:
          python_version: ${{ inputs.python_version }}
          requirements_file: ${{ inputs.requirements_file }}

      - uses: ./coretide/Pipelines/GitHub/framework-setup
        name: Framework Setup
        id: framework_setup
        with:
          coretide_path: ${{ inputs.coretide_path }}
