name: Validation

on:
  workflow_call:
    secrets:
      AZURE_TENANT_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_CLIENT_SECRET:
        required: false

    inputs:
      python_version:
        type: string
        required: true
      requirements_file:
        type: string
        required: true
      coretide_ref:
        type: string
        required: true
      coretide_path:
        type: string
        required: true
      deployment_plan:
        type: string
        required: true
      azure_workspace_id:
        type: string
        description: "Azure Workspace ID"
        required: false
      azure_subscription_id:
        type: string
        description: "Azure Subscription ID"
        required: false

jobs:
  Validation:
    name: OpenTide Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: ${{ inputs.coretide_path }}
          ref: ${{ inputs.coretide_ref }}

      - uses: ./coretide/Pipelines/GitHub/tide-setup
        name: Tide Setup
        id: tide_setup
        with:
          python_version: ${{ inputs.python_version }}
          requirements_file: ${{ inputs.requirements_file }}

      - uses: ./coretide/Pipelines/GitHub/validation-schema
        name: Run OpenTide Object Validation
        id: object_validation

      - uses: ./coretide/Pipelines/GitHub/check-mdr-changes
        name: Check MDR Changes
        id: detect

      - name: set_secrets
        shell: bash
        run: |
          env | sort | while IFS= read -r line; do
            if [[ "$line" == *"="* ]]; then
              key=$(echo "$line" | cut -d '=' -f 1)
              value=$(echo "$line" | cut -d '=' -f 2-)
              value=$(echo "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
              echo "$key=\"$value\"" >> $GITHUB_OUTPUT
            else
              echo "$line" >> $GITHUB_OUTPUT
            fi
          done
          cat $GITHUB_OUTPUT

      - uses: ./coretide/Pipelines/GitHub/validation-query
        name: Run OpenTide Query Validation
        id: query_validation
        with:
          deployment_plan: ${{ inputs.deployment_plan }}
          azure_workspace_id: ${{ inputs.azure_workspace_id }}
          azure_subscription_id: ${{ inputs.azure_subscription_id }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
