name: Validation

on:
  workflow_call: {}

jobs:
  Validation:
    name: OpenTide Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare HEAD to HEAD~1

      - name: Checkout Tide Core
        uses: actions/checkout@v4
        with:
          repository: OpenTideHQ/CoreTide
          path: ${{ env.CORETIDE_PATH }}
          ref: ${{ env.CORETIDE_REF }}

      - uses: ./coretide/Pipelines/GitHub/tide-setup
        name: Tide Setup
        id: tide_setup

      - uses: ./coretide/Pipelines/GitHub/validation-schema
        name: Run OpenTide Object Validation
        id: object_validation

      - uses: ./coretide/Pipelines/GitHub/check-mdr-changes
        name: Check MDR Changes
        id: detect

      - uses: ./coretide/Pipelines/GitHub/validation-query
        name: Run OpenTide Query Validation
        id: query_validation
